export enum CategoryArticleEnum {
    HTML = 'Html',
    CSS = 'Css',
    FRONTEND = 'Front-end',
    BACKEND = 'Back-end',
    BOOTSTRAP = 'Bootstrap',
    JAVASCRIPT = 'JavaScript',
    JQUERY = 'Jquery',
    REACT = 'React',
    ANGULAR_JS = 'Angular',
    JSON = 'Json',
    AJAX = 'Ajax',
    PYTHON = 'Python',
    JAVA = 'Java',
    C = 'C',
    C_PLUS_PLUS = 'C++',
    C_SHARP = 'C#',
    R = 'R',
    KOTLIN = 'Kotlin',
    GO = 'Go',
    DJANGO = 'Django',
    TYPESCRIPT = 'TypeScript',
    SQL = 'Sql',
    MYSQL = 'MySql',
    PHP = 'Php',
    ASP = 'Asp',
    NODE_JS = 'Nodejs',
    RASPBERRY_Pi = 'Raspberry Pi',
    GIT = 'Git',
    AWS_CLOUD = 'Aws Cloud',
    OTHER = 'Outra'
  }
  
export enum UserRoleEnum {
  USER = 'User',
  MODERATOR = 'Moderator',
}